const [SAVE_USER,
  REMOVE_USER,
  ADD_CATEGORY_SUCCESS,
  GET_CATEGORY_SUCCESS,
  ADD_SUB_CATEGORY_SUCCESS,
  GET_SUB_CATEGORY_SUCCESS,
  UPDATE_SUB_CATEGORY_NAME_SUCCESS,
  UPDATE_CATEGORY_NAME_SUCCESS]
  = ['SAVE_USER',
  'REMOVE_USER',
  'ADD_CATEGORY_SUCCESS',
  'GET_CATEGORY_SUCCESS',
  'ADD_SUB_CATEGORY_SUCCESS',
  'GET_SUB_CATEGORY_SUCCESS',
  'UPDATE_SUB_CATEGORY_NAME_SUCCESS',
  'UPDATE_CATEGORY_NAME_SUCCESS'];

export {
  SAVE_USER,
  REMOVE_USER,
  GET_CATEGORY_SUCCESS,
  GET_SUB_CATEGORY_SUCCESS,
  ADD_CATEGORY_SUCCESS,
  ADD_SUB_CATEGORY_SUCCESS,
  UPDATE_SUB_CATEGORY_NAME_SUCCESS,
  UPDATE_CATEGORY_NAME_SUCCESS
};